# Generated by Django 5.1.3 on 2024-12-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.PositiveIntegerField(),
        ),
    ]
